# -*- coding: utf-8 -*-
"""functions_visualization.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwjW5AZXMsSk0yQg4oQRe-rfQYn1Jy7B
"""

'''이 파일은 전반적으로 ai의 도움을 많이 받았습니다 - 그래프 그리는 부분'''

import matplotlib.pyplot as plt


# 실험 1, 2, 3, 4 각각의 결과를 출력하는 그래프

def plot_test_accuracy(results_dict, param_name, x_label, title):
    """
    입력:
        results_dict: 실험 결과 딕셔너리
        param_name: 파라미터 이름 (예: 'hidden_size', 'hidden_layers', 'dropout')
        x_label: x축 레이블
        title: 그래프 제목
    """
    # 데이터 추출
    results = results_dict['results']
    params = sorted(results.keys())
    test_accs = [results[p]['final_test_acc'] for p in params]

    # 그래프 그리기
    plt.figure(figsize=(10, 6))
    plt.plot(params, test_accs, 'b-o', linewidth=2, markersize=8)
    plt.title(title, fontsize=14, fontweight='bold')
    plt.xlabel(x_label, fontsize=12)
    plt.ylabel('Test Accuracy (%)', fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

    # 최적값 출력
    best_param = results_dict[f'best_{param_name}']
    best_acc = results_dict['best_accuracy']
    print(f"최고 Test 정확도를 만드는 {x_label}: {best_param}")
    print(f"최고 Test 정확도: {best_acc:.2f}%")


# 실험 2, 4를 비교하는 그래프

def plot_dropout_comparison(results_exp2, results_exp4):
    """
    입력:
        results_exp2: 실험 2 결과 (Dropout 없음)
        results_exp4: 실험 4 결과 (Dropout 있음)
    """
    # 데이터 추출
    results2 = results_exp2['results']
    results4 = results_exp4['results']
    layers = sorted(results2.keys())
    test_accs_no_dropout = [results2[l]['final_test_acc'] for l in layers]
    test_accs_with_dropout = [results4[l]['final_test_acc'] for l in layers]

    # 그래프 그리기
    plt.figure(figsize=(10, 6))
    plt.plot(layers, test_accs_no_dropout, 'b-o', linewidth=2,
             markersize=8, label='No Dropout (Exp 2)')
    plt.plot(layers, test_accs_with_dropout, 'r-s', linewidth=2,
             markersize=8, label='With Dropout (Exp 4)')
    plt.title('Performance Comparison: Dropout Effect', fontsize=14, fontweight='bold')
    plt.xlabel('Number of Hidden Layers', fontsize=12)
    plt.ylabel('Test Accuracy (%)', fontsize=12)
    plt.legend(fontsize=11)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

    # 결과 출력
    print(f"[Dropout 없음] 최고 Number of Hidden Layers: {results_exp2['best_hidden_layers']}, 정확도: {results_exp2['best_accuracy']:.2f}%")
    print(f"[Dropout 있음] 최고 Number of Hidden Layers: {results_exp4['best_hidden_layers']}, 정확도: {results_exp4['best_accuracy']:.2f}%")